version: "3.7"

services:
  database_banco:
    image: postgres
    container_name: banco
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=banco
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

volumes:
  pgdata:
    driver: local
